language: generic
sudo: required
services:
- docker
env:
  matrix:
  - IMAGE=latest  TESTS="01 02 03 04 10 11"
  - IMAGE=latest  TESTS="12 13 15 17 18"
  - IMAGE=latest  TESTS=20
  - IMAGE=latest  TESTS="30 31"
  - IMAGE=latest  TESTS=50
  - IMAGE=latest  TESTS="70 99"

before_script:
  - docker pull fedora:$IMAGE
  - git pull --depth=100
  - |
    git describe --abbrev=0 --tags || :
    git describe --tags || :

script:
- docker run --privileged -it -v $(pwd)/:/dracut fedora:$IMAGE /dracut/fedora-test.sh $IMAGE-$$ "$TESTS"

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/effa917ca3e0ed5fd00e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

