name: Container
on:
    schedule:
        -  cron: '30 11 * * *'   # every day at 11:30 UTC
    push:
        branches: [ main ]
        paths:
            - 'test/container/**'
            - '.github/workflows/container.yml'
    pull_request:
        branches: [ main ]
        paths:
            - 'test/container/**'
            - '.github/workflows/container.yml'

permissions:
    packages: write
    contents: read

jobs:
    arm64:
        if: github.repository == 'dracut-ng/dracut-ng' || vars.CONTAINER == 'enabled'
        name: ${{ matrix.config.tag }} on ${{ matrix.config.platform }}
        runs-on: ubuntu-latest
        concurrency:
            group: arm64-${{ github.workflow }}-${{ github.ref }}-${{ matrix.config.dockerfile }}
            cancel-in-progress: true
        strategy:
            fail-fast: false
            matrix:
                config:
                    - { dockerfile: 'Dockerfile-Debian',            tag: 'debian',     platform: 'linux/arm64,linux/amd64' }
                    - { dockerfile: 'Dockerfile-Fedora-latest',     tag: 'fedora',     platform: 'linux/arm64,linux/amd64' }
        steps:
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3
                with:
                    platforms: ${{ matrix.config.platform }}
            -   name: Check out the repo
                uses: actions/checkout@v4
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -   name: Set up env
                run: echo "repository_owner=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
            -   name: Build and Push Container
                uses: docker/build-push-action@v5
                with:
                    file: test/container/${{ matrix.config.dockerfile }}
                    tags: ghcr.io/${{env.repository_owner}}/${{ matrix.config.tag }}:latest
                    push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
                    platforms: ${{ matrix.config.platform }}

    amd64:
        if: github.repository == 'dracut-ng/dracut-ng' || vars.CONTAINER == 'enabled'
        name: ${{ matrix.config.tag }} on ${{ matrix.config.platform }}
        runs-on: ubuntu-latest
        concurrency:
            group: amd64-${{ github.workflow }}-${{ github.ref }}-${{ matrix.config.dockerfile }}
            cancel-in-progress: true
        strategy:
            fail-fast: false
            matrix:
                config:
                    - { dockerfile: 'Dockerfile-OpenSuse-latest',   tag: 'opensuse',   platform: 'linux/amd64' }
                    - { dockerfile: 'Dockerfile-Arch',              tag: 'arch',       platform: 'linux/amd64' }
                    - { dockerfile: 'Dockerfile-Gentoo',            tag: 'gentoo',     platform: 'linux/amd64' }
                    - { dockerfile: 'Dockerfile-Ubuntu',            tag: 'ubuntu',     platform: 'linux/amd64' }
                    - { dockerfile: 'Dockerfile-alpine',            tag: 'alpine',     platform: 'linux/amd64' }
                    - { dockerfile: 'Dockerfile-Void',              tag: 'void',       platform: 'linux/amd64' }
        steps:
            -   name: Check out the repo
                uses: actions/checkout@v4
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -   name: Set up env
                run: echo "repository_owner=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
            -   name: Build and Push Container
                uses: docker/build-push-action@v5
                with:
                    file: test/container/${{ matrix.config.dockerfile }}
                    tags: ghcr.io/${{env.repository_owner}}/${{ matrix.config.tag }}:latest
                    push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
                    platforms: ${{ matrix.config.platform }}
